spring:
  application:
    name: devops
  datasource:
    username: xx
    password: xx
    url: jdbc:mysql://localhost:3306/xx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080


